### ISSUE TITLE
Meeting regarding CD101 - 09/02/2018

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/community-committee#1]
## Meeting regarding CD101
Points to discuss on - 
- Distribution of duties (Classes, Monitoring, Attendance, PSs, Office Hours etc)
- Final Syllabus Audit
- Students filter process
- etc

Timings - 2:30 onwards

Venue - My room

Docs Link - https://docs.google.com/document/d/1zVGaRVnr5qSkr3snZT2YXUtHEVlnV6PYzBTnKRHCQSI/edit?usp=sharing

**Comment by ShivSoni5** [comment]
Tomorrow?

**Comment by maddhruv** [comment]
Yes

**Comment by ShivSoni5** [comment]
Okay

**Comment by ShivSoni5** [comment]
Any progress?

**Comment by ShivSoni5** [comment]
Any progress?

**Comment by ShivSoni5** [comment]
Any progress?

**Comment by ShivSoni5** [comment]
Any progress?

**Comment by ShivSoni5** [comment]
Any progress?

**Comment by maddhruv** [comment]
We will go to classes of IV sem CSE on Monday and will stick to the idea we discussed yesterday.
Filter students on different criteria

**Comment by maddhruv** [comment]
@gauravjain99 can be closed?
