### ISSUE TITLE
Community Committee Restructuring Effort Meeting - Discussion with Elected Members

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/community-committee#12]
## Agenda

- [x] Discussion of duties and responsibilities you shall share.
- [x] Potential courses
- [x] Potential initiatives and events
- [x] Promotion, Outreach & orientation
- [x] How to deal with college authorities
- [x] Rest team & volunteers

## Invited
@accakks 
@amritsrivastava
@samyak360

## Date and Time
TBD

**Comment by maddhruv** [comment]
I am travelling these days a lot
cant say about the day at this point

**Comment by accakks** [comment]
@maddhruv Just inform whichever day you're free this week. If its in evening after 8, would work for me on any day.

I said 8-9pm because if someone is interning or anything, they'd be free till this time.

**Comment by samyak360** [comment]
Any day after 8 would work for me as well.

**Comment by accakks** [comment]
How about 19 June 8pm?

**Comment by maddhruv** [comment]
Oh?
I am really very sorry
I forgot about this part!

Very busy these days, don't even brush in the mornings 😋

If I get a little time today, can I make a call if you all three are available

**Comment by accakks** [comment]
Can you do after 9. I'm available.

**Comment by maddhruv** [comment]
I can't say about my time 😓😓

**Comment by amritsrivastava** [comment]
I'm not available today.
Can we do this discussion tommorrow b/w 10 am to 12pm

**Comment by maddhruv** [comment]
I will have to look out!
Will be travelling tomorrow, can't say anything

**Comment by samyak360** [comment]
Even I am not available today . We should do this discussion on 19 then.

**Comment by maddhruv** [comment]
feel free to add agenda items in the description.

**Comment by maddhruv** [comment]
have edited the agenda's items to _done_

**Comment by maddhruv** [comment]
The meeting is done on the phone
no minutes were recorded

Closing
