### ISSUE TITLE
Meeting regarding CD101 / 19/02/2018

### ISSUE THREAD

**Issue by gauravjain99** [CodeDocsJECRC/community-committee#2]
In this meeting, we are going to discuss the following : 

1.  How to execute everything
2.  How all responsibilities will be shared 

The venue will be Dhruv Jain's room 
Timings --- 11:30 AM to 12:30 PM

**Comment by maddhruv** [comment]
This is a common time for all of us.
Please everyone be present tomorrow, no excuses

**Comment by 19ANDY** [comment]
sure sir

**Comment by ShivSoni5** [comment]
I'll be tuition at that time!

**Comment by gauravjain99** [comment]
Try everything in your power to be here at 11:30.

**Comment by gauravjain99** [comment]
Try everything in your power to be here at 11:30.

**Comment by gauravjain99** [comment]
Try everything in your power to be here at 11:30.

**Comment by gauravjain99** [comment]
Try everything in your power to be here at 11:30.

**Comment by gauravjain99** [comment]
Try everything in your power to be here at 11:30.

**Comment by gauravjain99** [comment]
My preferred venue is Cafeteria

**Comment by maddhruv** [comment]
Cafeteria is a crowdy and public place.
How about finding a free lecture hall?

**Comment by maddhruv** [comment]
@gauravjain99 can be closed?
