### ISSUE TITLE
CommComm Meeting - 25/06/2018 - 20:30-21:30

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/community-committee#26]
## Agenda
- Introducing Mascot #10 
- Orientation #13 
- Courses to initiate #14 
- Methods to indulge students in CodeDocs activities #15 
- New members inclusion #19 
- Open source projects under CodeDocs #20 

## Invited
- @maddhruv - Dhruv Jain
- @accakks - Aakanksha Jain
- @amritsrivastava - Amrit Srivastava

**Comment by accakks** [comment]
#21 Remind me of taking notes tomm

**Comment by accakks** [comment]
MoM added #25
