### ISSUE TITLE
Communication platform for CodeDocs

### ISSUE THREAD

**Issue by accakks** [CodeDocsJECRC/community-committee#28]
Currently we have two whatsapp groups. 

I suggest using **telegram**

- Group members limit is `10000`
- Admin can `delete` messages
- As `easy to use` as WhatsApp, unlike slack etc
- Options for `poll, bot` etc

**Comment by Man-Jain** [comment]
I think that we should continue using Slack only as it is more professional than using Telegram. Telegram feels to be an odd choice for a team collaboration app. Also Slack is used more professional environments. So it would be good for us to get familiar with using it.

**Comment by accakks** [comment]
Yes we had slack earlier but no one responsive so for time being, created Whatsapp groups. Slack also has some notifications problems. Lets discuss this more on 6 July meeting.
