### ISSUE TITLE
Meeting regarding CD101 - 12/03/2018

### ISSUE THREAD

**Issue by gauravjain99** [CodeDocsJECRC/community-committee#3]
It has been long we haven't met. This meeting is focused on various new initiatives and changes in the community, problems students are facing and how to resolve them.
## Time
10:00 PM

## Agenda
- Regular classes of CD101
- Assignment submission problems
- Duties allocation revision for CD101
- New members to team
- Projects initiation
- Github activity summary of team members (also us)
- Website maintenance

## Invited members
- @CodeDocsJECRC/community-committee 

## Links
- Zoom link - https://zoom.us/j/862219638
- Google Docs Link - https://docs.google.com/document/d/1ZXYBxIXYzUDAk4PYC56qYrlybc5kVm3WbO5PEHeLMzs/edit?usp=sharing

**Comment by gauravjain99** [comment]
if anyone wants to add any other topic for discussion, please mention

**Comment by maddhruv** [comment]
Sure, will be there

**Comment by akshaysharma2277** [comment]
Yup will be there.

**Comment by Aksh-a1** [comment]
will be here, in front of my webcam!

**Comment by gauravjain99** [comment]
join now - https://zoom.us/j/862219638

**Comment by gauravjain99** [comment]
https://zoom.us/j/924212566

**Comment by maddhruv** [comment]
@gauravjain99 can be closed?
