### ISSUE TITLE
CommComm Meeting - 30/07/2018 - 20:30-21:30

### ISSUE THREAD

**Issue by accakks** [CodeDocsJECRC/community-committee#31]
### Agenda
- Beginning Promotion & tasks division
- Decision on class start date & methodology 
- A brief about orientation -> GSoC event change

### Attendees 
CodeDocs team

**Comment by maddhruv** [comment]
The same would be on zoom or phone?

**Comment by amritsrivastava** [comment]
I think zoom would be a better option, if there are more peoples.
