### ISSUE TITLE
[proposal] JECRC Website

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/community-committee#32]
Revamping the JECRC website into an open source and community driven website that shall contain more available facilities and options to the college -
Some of the proposed features can be -
- **Department wise sections**
    - News
    - Posts
    - Time tables
    - Notes from faculties
    - calendar
    - activities
- Administration
- Faculties Directory
    - Contact details (mail, phone)
    - sitting
- Students Directory
    - details (year/branch, email)
    - personal achievements
    - portfolio
- Clubs
    - zarurat, aashayein, soch, codedocs, fnf, etc
    - details
    - team
    - photos
- Time table
    - all classes and branches time table
- Cafe
    - available menu
    - buy/pay online
- Campus Life
    - activites
    - infrastructure
- Alumni
    - directory
    - achievements
- Startups
    - links and portfolios
- Social Media and News

**Comment by accakks** [comment]
@maddhruv People are already building college & department website which is 75% complete by now as Amrit told me yesterday. 
Almost similar to the one you are proposing.

**Comment by maddhruv** [comment]
who are these people?
which all departments are they covering?

**Comment by accakks** [comment]
All departments. 8-10 people I guess. 
They've been working from a month. 
Amrit, Aditya, Arpit are part of team.
I guess I told you about this.

**Comment by aditya81070** [comment]
@accakks Please check codeDocs content at [jecrc website](https://jecrcwebsite.herokuapp.com) in computer science and if you find anything to add please tell me.

**Comment by accakks** [comment]
Looks good to me @aditya81070

**Comment by aditya81070** [comment]
@accakks  okay then.

**Comment by aditya81070** [comment]
@maddhruv  closing this issue as the website has hosted.
