### ISSUE TITLE
To develop a payment Gateway for JECRC college Events

### ISSUE THREAD

**Issue by nd-singh** [CodeDocsJECRC/community-committee#37]
Whenever an event takes place in our college, the fees to be taken from the students is through different mediums such as cash, paytm etc. and record of each of these payments have to be kept separately and finally submitted to the faculty coordinator. Why not have a common platform for all the events (maybe an app or website) where the fees or any contribution can directly go to concerned person?

Ever wondered! how can we make it personalized according to events requirement? So this is the opportunity for everyone who can contribute to this open source project and can work as a team to simplify the payments solution for events in our college. 

We always look for some live or major projects so why not consider this project which will even help our college and at the same time will help you to enhance your skills.
Your suggestions are always welcomed! Feel free to contact so that we can contribute to this project and take this project to the next level!

**Comment by maddhruv** [comment]
@nd-singh @CodeDocsJECRC/android @CodeDocsJECRC/community-committee 
please proceed :arrow_right:  https://github.com/CodeDocsJECRC/JECRC-Pay
Best of luck :smile:

**Comment by accakks** [comment]
@nd-singh  I guess you might be having some code ready for this right? You can prepare contributing guidelines and push it. (Assuming you built something like this in IT Hackathon)

**Comment by nd-singh** [comment]
@accakks yes I have built the code in the IT Hackathon I will be pushing it soon!

**Comment by nd-singh** [comment]
@maddhruv @accakks @Abhimanyu121 @soumilk @ukigos I would like to know that payment's gateway Integration requires some business documents proofs for eg: In my app, I had integrated paytm's SDK which was giving credentials only to the merchant account holder but for the developers, it provides sandbox credentials which can be used as testing and staging. So I used the sandbox credentials for testing but we need original merchant account holder credentials which will be provided only after the verification of business documents of the account holder for implementing it in the whole college. 
If you guys know better options other than paytm as a payment's gateway (as other requires some kind of transaction fee per transaction), please suggest something! or what else can be done.
I have the code ready with sandbox credentials using paytm's gateway.

**Comment by maddhruv** [comment]
Please discuss all these issues in the repository I have created for the same.
Hope to see you there
