### ISSUE TITLE
Develop an Attendance Management System

### ISSUE THREAD

**Issue by Man-Jain** [CodeDocsJECRC/community-committee#38]
At present the Attendance of each student is manually taken by teachers and then updated online. This doubles and even triples the effort and makes it very difficult and time-consuming for teachers. The college is now seeking for a fully software solution. We can develop an open source project for the same.

# User Requirements:- 

These are the basic user requirements more can be found out by asking the faculty.

1. HoD should be able to upload list of students of all classes in excel format 
2. HoD should register the members of faculty in attendance management application using excel sheet 
3. Faculty should be able to register and add the subjects and time table for subject he is taking 
4. Faculty should be able to take attendance through mobile.(Simple and compact GUI) 
5. Head of Department should be able to send the mail the attendance of the student to his/her parents. 
6. HoD should be allowed to filter the mails based on some attendance threshold criteria. 
7. Attendance management system should show all those students who are debarred from examination.

There will be two parts of the app :- 
1. Web Portal
2. Android App

# Tech to Use :-

1. The Web Portal to made can be made in either Python or Node.js in backend. Whereas front-end can be basic with minimal styling like Bootstrap.
2. The app will be made in Android.

**Comment by maddhruv** [comment]
@Man-Jain @CodeDocsJECRC/android @CodeDocsJECRC/community-committee 
Please proceed :arrow_right: https://github.com/CodeDocsJECRC/JECRC-Attendance
Best of luck :zap:
