### ISSUE TITLE
Add email

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/community-committee#7]
@satan17 add your email address in the table and also update your name in the https://github.com/CodeDocsJECRC/society repository

**Comment by amritsrivastava** [comment]
@samyak360 kindly update your details in the society repo.
https://github.com/CodeDocsJECRC/society

**Comment by samyak360** [comment]
I am having my details in the members list

On Sat, Jun 23, 2018 at 11:45 PM, Amrit Srivastava <notifications@github.com

**Comment by amritsrivastava** [comment]
Actually I attached the wrong link, update your details here https://github.com/CodeDocsJECRC/community-committee

**Comment by amritsrivastava** [comment]
@satan17 also update your email here https://github.com/CodeDocsJECRC/community-committee

**Comment by satan17** [comment]
access denied to @satan17

**Comment by amritsrivastava** [comment]
Make a PR.

With Regards,
Amrit Srivastava

**Comment by maddhruv** [comment]
@satan17 do via a forked repo,

**Comment by amritsrivastava** [comment]
@maddhruv kindly close this issue.
