### ISSUE TITLE
Meeting regarding upgrading some parts of CodeDocs - 16-03-2018

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/community-committee#9]
The meeting is focused on various upgrades and additions to be done in CodeDocs.
## Time
22:00

## Agenda
- Membership class #4 
- Team members directory #5 
- Designations for CommComm members on Chair #6 
Can be discussed
- UI/UX Chapter

## Invited Members
- @CodeDocsJECRC/community-committee 

## Links
Zoom link - *will be shared before 5 minutes*

Google Docs Link - https://docs.google.com/document/d/1rDCab2H1x7jTVa3nwvPX570SXct8fazXzqptapFCtH8/edit?usp=sharing

**Comment by satan17** [comment]
Done

**Comment by maddhruv** [comment]
Also check #4, #5, #6

**Comment by ShivSoni5** [comment]
Meeting?

**Comment by gauravjain99** [comment]
https://zoom.us/j/171177606
Join

**Comment by gauravjain99** [comment]
https://zoom.us/j/818511641
